### ISSUE TITLE
Error in preprocessing, number of samples 0

### ISSUE THREAD

**Issue by moonlight2397** [nlpat/MEGA-DT#1]
I am trying to run the milnet pretrained model using --eval_mil, for which I am running --prep to create the input files. 
The input for --prep is a text file "eval.txt" with sentiment label (0-2) and doc id on one line, the EDUs on the following lines. Each set of document EDUs, id, and sentiment label is separated by a blank line. 

No errors are shown during preprocessing. But when I try to run --eval_mil, I get the following error:
Not sure what is going wrong. If I don't shuffle the dataset, I get a different error, about mismatched tensor dimensions. I tried not shuffling it as I read about issues with custom datasets in torch and the random sampler.

There is something wrong with the creation of the test_idx2data.dict . In the definition of the DataFormat class, the length is set using self.idx2doc_id, but this value is 0. 

Am I doing something wrong?

ERROR 1
`Traceback (most recent call last):
  File "main.py", line 180, in <module>
    args.gru_hidden_size, args.classes)
  File "/Users/*/MEGA-DT/src/mil/eval.py", line 58, in test_doc_lvl
    shuffle=True)
  File "/Users/*/MEGA-DT/src/mil/training.py", line 19, in _data_loader
    num_workers=cpu_workers)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 213, in __init__
    sampler = RandomSampler(dataset)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 94, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0`

ERROR 2
`Evaluating model on document level...
Traceback (most recent call last):
  File "main.py", line 180, in <module>
    args.gru_hidden_size, args.classes)
  File "/root/megadt/src/mil/eval.py", line 70, in test_doc_lvl
    save_dir+model_ext+'/wordNet_states.pt'))
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1224, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for AttentionWordRNN:
	size mismatch for lookup.weight: copying a param with shape torch.Size([400001, 300]) from checkpoint, the shape in current model is torch.Size([4180, 300]).`

**Comment by nlpat** [comment]
This error occurs because the MIL component has not been re-trained. The default model in this repository is pre-trained on the 5-class Yelp'13 dataset, therefore, preprocessing a dataset with ternary sentiment labels does not contain the right number of output classes for the pre-trained model. To run --mil_eval you should first run --mil to train the MIL component on the 3-class task.

**Comment by moonlight2397** [comment]
Hi Patrick,

Earlier you said that you can send me the EDU segmented Yelp dataset. Can
you please send it to me?

Also, I tried just changing the labels to fit the 0-4 classification task,
to check if I am facing any other issues, and I still get the same error:
Shouldn't it work if I have a file with labels between 0-4? Or will it only
work if I retrain it on the 3 class task?


RuntimeError: Error(s) in loading state_dict for AttentionWordRNN:
	size mismatch for lookup.weight: copying a param with shape
torch.Size([400001, 300]) from checkpoint, the shape in current model
is torch.Size([4180, 300]).

------------------------------


Best,
Sarika
